apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: simple-server
  name: simple-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-server
  template:
    metadata:
      labels:
        app: simple-server
    spec:
      containers:
      - image: surjection/stable-server:latest
        name: stable-server
        ports:
        - containerPort: 8090
