apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-server
  name: simple-server
spec:
  type: NodePort
  ports:
  - port: 8090
    nodePort: 30000
    protocol: TCP
    targetPort: 8090
  selector:
    app: simple-server
